node {
    stage('Checkout') {
        deleteDir()
        git branch: 'main', url: 'https://github.com/jandresleiva/groceries.git'
    }
    stage('Build') { 
        sh 'dotnet build'
    }
    stage('Test') {
        sh "run_tests.bash"
    }
    post {
        always{
            xunit (
                thresholds: [ skipped(failureThreshold: '0'), failed(failureThreshold: '0') ],
                tools: [ BoostTest(pattern: 'boost/*.xml') ]
            )
        }
    }
}