node {
    stage('Checkout') {
        git url: 'https://github.com/jandresleiva/groceries.git'
        sh 'git checkout main'
    }
    stage('Build') { 
        sh 'dotnet build'
    }
    stage('Test') {
        sh 'cd GroceriesTesting'
        sh 'dotnet test'
    }
    if (currentBuild.currentResult == 'SUCCESS') {
        stage('Deploy') {
            echo "SUCCEDED!!!"
        }
    }
}